version: 1
builder:
  configs:
    - documentation_targets: []
      swift_version: "5.9"
    - documentation_targets: []
      swift_version: "5.10"
    - documentation_targets: []
      swift_version: "6.0"
    - documentation_targets: []
      swift_version: "6.1"
metadata:
  exclude_branches:
    - main
    - version-config
